[package]
name = "ngdp-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "NGDP client CLI for Cascette"
keywords = ["ngdp", "cli", "blizzard", "wow", "casc"]
categories = ["command-line-utilities", "game-development"]

[lib]
name = "ngdp_client"
path = "src/lib.rs"

[[bin]]
name = "ngdp"
path = "src/main.rs"

[dependencies]
clap = { workspace = true, features = ["derive", "cargo", "env"] }
comfy-table = "7.1.1"
owo-colors = { version = "4.2.1", features = ["supports-colors"] }
ribbit-client = { path = "../ribbit-client" }
tact-client = { path = "../tact-client" }
ngdp-bpsv = { path = "../ngdp-bpsv" }
ngdp-cache = { path = "../ngdp-cache" }
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true
tracing-subscriber.workspace = true
thiserror.workspace = true
serde = { workspace = true, features = ["derive"] }
serde_json = "1.0"
dirs.workspace = true
reqwest = { version = "0.12", features = ["json"] }
base64 = "0.22"
x509-cert = "0.2"
der = "0.7"

[dev-dependencies]
assert_cmd = "2.0"
predicates = "3.1"
tempfile = "3.17"
tracing-subscriber.workspace = true