[package]
name = "tact-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
repository.workspace = true
description = "TACT protocol client for Cascette"

[dependencies]
reqwest = { version = "0.12", features = ["json", "stream"] }
thiserror.workspace = true
tokio = { version = "1.45", features = ["full"] }
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true