[package]
name = "tact-client"
version.workspace = true
authors.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
repository.workspace = true
homepage.workspace = true
description = "TACT protocol client for Cascette"

[dependencies]
ngdp-bpsv = { path = "../ngdp-bpsv" }
reqwest = { version = "0.12", features = ["json", "stream"] }
thiserror.workspace = true
tokio = { workspace = true, features = ["full"] }
tracing.workspace = true

[dev-dependencies]
criterion.workspace = true
tracing-subscriber.workspace = true
