---
name: Release

on:
  push:
    tags:
      - 'v[0-9]+.*'
      - 'ngdp-client-v[0-9]+.*'

  workflow_dispatch:
    inputs:
      version:
        description: 'Version to release (e.g., 0.1.0)'
        required: true
        type: string
      release-type:
        description: 'Release type'
        required: true
        type: choice
        options:
          - all
          - libraries
          - cli

env:
  CARGO_TERM_COLOR: always
  RUST_BACKTRACE: 1
  RUSTFLAGS: -D warnings
  CARGO_INCREMENTAL: 0

permissions:
  contents: write
  packages: write

jobs:
  determine-release-type:
    name: Determine Release Type
    runs-on: ubuntu-latest
    outputs:
      release-libraries: ${{ steps.determine.outputs.release-libraries }}
      release-cli: ${{ steps.determine.outputs.release-cli }}
      version: ${{ steps.determine.outputs.version }}
    steps:
      - name: Determine what to release
        id: determine
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            VERSION="${{ inputs.version }}"
            RELEASE_TYPE="${{ inputs.release-type }}"
          else
            # Parse tag to determine release type
            TAG="${GITHUB_REF#refs/tags/}"
            if [[ "$TAG" == ngdp-client-v* ]]; then
              VERSION="${TAG#ngdp-client-v}"
              RELEASE_TYPE="cli"
            else
              VERSION="${TAG#v}"
              RELEASE_TYPE="all"
            fi
          fi

          echo "version=$VERSION" >> $GITHUB_OUTPUT

          case "$RELEASE_TYPE" in
            all)
              echo "release-libraries=true" >> $GITHUB_OUTPUT
              echo "release-cli=true" >> $GITHUB_OUTPUT
              ;;
            libraries)
              echo "release-libraries=true" >> $GITHUB_OUTPUT
              echo "release-cli=false" >> $GITHUB_OUTPUT
              ;;
            cli)
              echo "release-libraries=false" >> $GITHUB_OUTPUT
              echo "release-cli=true" >> $GITHUB_OUTPUT
              ;;
          esac

  # Release libraries to crates.io
  release-libraries:
    name: Release Libraries
    needs: determine-release-type
    if: needs.determine-release-type.outputs.release-libraries == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Install Rust toolchain
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: stable

      - name: Cache Rust dependencies
        uses: Swatinem/rust-cache@v2

      - name: Verify versions match
        run: |
          VERSION="${{ needs.determine-release-type.outputs.version }}"
          for crate in ngdp-bpsv ribbit-client tact-client ngdp-cdn ngdp-cache ngdp-client; do
            CRATE_VERSION=$(cargo metadata --format-version 1 --no-deps | jq -r ".packages[] | select(.name == \"$crate\") | .version")
            if [[ "$CRATE_VERSION" != "$VERSION" ]]; then
              echo "Version mismatch for $crate: expected $VERSION, found $CRATE_VERSION"
              exit 1
            fi
          done

      - name: Run tests
        run: cargo test --all-features --workspace

      - name: Publish to crates.io
        env:
          CARGO_REGISTRY_TOKEN: ${{ secrets.CRATES_IO_TOKEN }}
        run: |
          # Publish in dependency order
          cargo publish -p ngdp-bpsv
          sleep 30  # Wait for crates.io to index
          
          cargo publish -p ribbit-client
          cargo publish -p tact-client
          sleep 30
          
          cargo publish -p ngdp-cdn
          cargo publish -p ngdp-cache
          sleep 30
          
          cargo publish -p ngdp-client

      - name: Create library release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: v${{ needs.determine-release-type.outputs.version }}
          name: cascette-rs v${{ needs.determine-release-type.outputs.version }}
          body: |
            ## Library Release v${{ needs.determine-release-type.outputs.version }}

            This release includes updates to all cascette-rs libraries:
            - ngdp-bpsv
            - ribbit-client
            - tact-client
            - ngdp-cdn
            - ngdp-cache
            - ngdp-client

            ### Installation

            Add to your `Cargo.toml`:
            ```toml
            [dependencies]
            ngdp-bpsv = "${{ needs.determine-release-type.outputs.version }}"
            ribbit-client = "${{ needs.determine-release-type.outputs.version }}"
            # ... other crates as needed
            ```

            See the [CHANGELOG](https://github.com/wowemulation-dev/cascette-rs/blob/main/CHANGELOG.md) for details.

  # Release CLI binaries
  release-cli:
    name: Release CLI
    needs: determine-release-type
    if: needs.determine-release-type.outputs.release-cli == 'true'
    uses: ./.github/workflows/release-cli.yml
    with:
      version: ${{ needs.determine-release-type.outputs.version }}
      dry-run: false
    secrets: inherit

  # Final success check
  release-success:
    name: Release Success
    if: always()
    needs: [determine-release-type, release-libraries, release-cli]
    runs-on: ubuntu-latest
    steps:
      - name: Check release status
        run: |
          echo "Release type determination: ${{ needs.determine-release-type.result }}"
          echo "Library release: ${{ needs.release-libraries.result }}"
          echo "CLI release: ${{ needs.release-cli.result }}"
          
          # Check if any required job failed
          if [[ "${{ needs.determine-release-type.outputs.release-libraries }}" == "true" ]] && [[ "${{ needs.release-libraries.result }}" != "success" ]]; then
            echo "Library release failed"
            exit 1
          fi
          
          if [[ "${{ needs.determine-release-type.outputs.release-cli }}" == "true" ]] && [[ "${{ needs.release-cli.result }}" != "success" ]]; then
            echo "CLI release failed"
            exit 1
          fi
          
          echo "All releases completed successfully!"